### ISSUE TITLE
Duvida Desafio 10

### ISSUE THREAD

**Issue by Leticiassb** [cami-la/Ganhando_Produtividade_com_Stream_API_Java#19]
Olá, Cami. Tudo bem?

Consegui resolver o desafio 10 porém gostaria de saber se há uma forma melhor para simplificar o código, sinto que repeti na verificação dos multiplos mas nao consegui pensar em outra forma de resolver. Pode me ajudar?

![image](https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/assets/164404350/bc9a31ba-d9f4-40ec-94b2-d03defa78c0a)

**Comment by Leticiassb** [comment]
Tive a mesma dúvida no 11, rsrs. Rodou mas tem como melhorar o código?
![image](https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/assets/164404350/fab53240-18de-48cb-bfeb-2f11ce095f99)

**Comment by esquilo11** [comment]
Fiz dessa forma.
![image](https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/assets/20381617/9f7ee4ee-14fd-42e0-8eab-aa031e1ad2aa)

Já que é uma "Filtragem" de elementos fiz criando um predicate com as especificações do enunciado

**Comment by esquilo11** [comment]
> Tive a mesma dúvida no 11, rsrs. Rodou mas tem como melhorar o código? ![image](https://private-user-images.githubusercontent.com/164404350/337828726-fab53240-18de-48cb-bfeb-2f11ce095f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTg4MjUsIm5iZiI6MTcxNzkxODUyNSwicGF0aCI6Ii8xNjQ0MDQzNTAvMzM3ODI4NzI2LWZhYjUzMjQwLTE4ZGUtNDhjYi1iZmViLTJmMTFjZTA5NWY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwNzM1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWQzOWMzMmZiZmZjNWFmNmIzNmZhZDQ4YzU4N2ZiMGFhZWQyMjFmODhlMDNiMDRkODVjNDU0NmRkMzI3NTU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0VePR9xFIYWSljSZRrSHPsCoktxrUqUeL-DwwZNiTp0)

Acabei vendo o seu antes da 11 e basicamente o que fiz foi encadear as funções que vc ultilizou. ligando map, diretamente após o reduce

System.out.println(  numerosInteirosRed.stream().map( n -> n*n).reduce(0, Integer::sum)  );

**Comment by Leticiassb** [comment]
Muito obrigada por compartilhar comigo! @esquilo11

**Comment by cami-la** [comment]
Oi, pessoal. Tudo certinho?

@Leticiassb Tem muitas formas de utilizar as funções do Stream API. Não se preocupe, com o tempo nós vamos aprendendo várias formas e vemos qual é a mais fácil, a mais performática...

Por exemplo, segue uma outra maneira:

```java
        List<Integer> numeros = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 4, 3);

        // Agrupa os números em duas listas: uma com múltiplos de 3 ou 5 e outra com os restantes
        Map<Boolean, List<Integer>> collectNumerosMultiplosDe3ou5 = numeros.stream()
                .collect(Collectors.groupingBy(i -> (i % 3 == 0 || i % 5 == 0)));

        // Extrai a lista com os números que são múltiplos de 3 ou 5
        List<Integer> multiplosDe3ou5 = collectNumerosMultiplosDou3E5.get(true);

        // Imprime a lista com os múltiplos de 3 ou 5
        System.out.println(multiplosDe3ou5);
```

E muito obrigada @esquilo11 pela disponibilidade em ajudar aqui nas issues. (:
