### ISSUE TITLE
Duvida Binary  Operator

### ISSUE THREAD

**Issue by LuizSorrentino** [cami-la/Ganhando_Produtividade_com_Stream_API_Java#20]
Tentei reproduzir o binary Operator na minha IDE e simplesmente da um warning sem proposta de solução. Eu posso até copiar do exemplor do GIT aqui que continua dando erro.

**Comment by cami-la** [comment]
> Tentei reproduzir o binary Operator na minha IDE e simplesmente da um warning sem proposta de solução. Eu posso até copiar do exemplor do GIT aqui que continua dando erro.

Olá, bom dia. 

1. Qual a versão do JDK que você está utilizando?
2. Poderia anexar um print da IDE?
3. O warning está impedindo de executar o código?

**Comment by LuizSorrentino** [comment]
versão 21.0.2

![Captura de tela 2024-06-12 110821](https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/assets/164554421/006b1fcc-80f7-4ea4-a37f-4a82b0f377e4)

o segundo warning ta escrito: The target type of this expression must be a functional interfaceJava(553648781)
sim, ele impede é o warning vermelho

**Comment by cami-la** [comment]
Certo, vamos tentar resolver.

1. No curso, eu acredito que utilizo o JDK 17. Recomendo permanecer na mesma versão.
2. Quando está apresentando essa ondulação vermelhinha, não é warning. Geralmente é erro de compilação. O warning geralmente não impede do código compilar e executar.
3. Acho que está faltando a importação da interface BinaryOperator.

`import java.util.function.BinaryOperator;`

Caso não funcione, por favor, me avisa que tento rodar localmente com o JDK 21 e vejo e se apresenta algo parecido aqui.

**Comment by LuizSorrentino** [comment]
![image](https://github.com/digitalinnovationone/ganhando_produtividade_com_Stream_API_Java/assets/164554421/ab731ce4-b2b2-46ad-9181-17e0deb7231f)
a importação esta dando esse erro agora. Mas eu fui fazer o desafio 3 e consegui normalmente que a função execute como esperado, acho que vou deixar para lá já que eu consegui em outro arquivo

**Comment by cami-la** [comment]
O erro está dizendo que o arquivo .java e a importação estão com os mesmos nomes, por isso está apresentando um conflito.

Tenta renomear o arquivo: 

1. seleciona o arquivo e pressiona F2, ou clica com o botão direito e clica na opção renomear. 
2. Troca para `BinaryOperatorEx.java`

**Comment by LuizSorrentino** [comment]
Nossa perfeito, Obrigado Cami!!
