### ISSUE TITLE
Desafio 11

### ISSUE THREAD

**Issue by cauelima1** [cami-la/Ganhando_Produtividade_com_Stream_API_Java#24]
Olá Cami,

Primeiramente muito obrigado pelas aulas.

Gostaria de tirar uma duvida sobre o desafio 11 (Soma dos quadrados da lista)).

Pensei nesta forma de resolver este problema mas o resultado está dando negativo.

public class Desafio11_somaDosQuadrados {
    public static void main(String[] args) {
        List<Integer> numeros = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 5, 4, 3);
        Integer numerosAoQuadrado = numeros.stream().reduce(0, (a, b) -> getSquare(a) + getSquare(b));
        System.out.println(numerosAoQuadrado);
    }

    private static Integer getSquare(int number) {
        return number*number;
    }
}

**Comment by fgmarcal** [comment]
olá, amigo. 
Aqui uma implementação minha usando apenas um método.

`    public static int sumOfSquares(List<Integer> list) {
        var sum = list.stream()
                .mapToInt(n -> n * n)
                .sum();
        return sum;
    }`

**Comment by cauelima1** [comment]
valeu amigo, muito boa sua solução!
